/* ============================================
   DALEXOR - Environment Configuration
   AUTO-GENERATED BY build.js - DO NOT EDIT MANUALLY
   
   This file is regenerated during Vercel build.
   Set environment variables in Vercel Dashboard:
   Project Settings > Environment Variables
   
   Required:
   - SUPABASE_URL
   - SUPABASE_ANON_KEY
   ============================================ */

window.__ENV__ = {
    SUPABASE_URL: '',
    SUPABASE_ANON_KEY: ''
};

// If empty, show error in console
if (!window.__ENV__.SUPABASE_URL) {
    console.error('⚠️ DALEXOR: Environment not configured. Run build.js or set Vercel env vars.');
}
