/* ============================================
   DALEXOR - Supabase Client
   Handles authentication, forms, and licensing
   ============================================ */

// Supabase Configuration - Loaded from env-config.js (generated by build.js)
// Set these in Vercel Dashboard: Project Settings > Environment Variables
// - SUPABASE_URL
// - SUPABASE_ANON_KEY
const SUPABASE_URL = window.__ENV__?.SUPABASE_URL;
const SUPABASE_ANON_KEY = window.__ENV__?.SUPABASE_ANON_KEY;

// Validate configuration
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('❌ DALEXOR: Supabase not configured!');
    console.error('   Set SUPABASE_URL and SUPABASE_ANON_KEY in Vercel environment variables.');
}

// Initialize Supabase Client
const supabase = (SUPABASE_URL && SUPABASE_ANON_KEY) 
    ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
    : null;

// ============================================
// AUTHENTICATION
// ============================================

const DalexorAuth = {
    // Current user
    currentUser: null,

    // Initialize auth state
    async init() {
        const { data: { session } } = await supabase.auth.getSession();
        this.currentUser = session?.user || null;
        
        // Listen for auth changes
        supabase.auth.onAuthStateChange((event, session) => {
            this.currentUser = session?.user || null;
            this.updateUI();
        });
        
        this.updateUI();
    },

    // Register new user
    async register(email, password, firstName, lastName, company = null) {
        try {
            // Create auth user
            const { data: authData, error: authError } = await supabase.auth.signUp({
                email,
                password,
                options: {
                    data: {
                        first_name: firstName,
                        last_name: lastName,
                        company: company
                    }
                }
            });

            if (authError) throw authError;

            // Create user profile in our users table
            if (authData.user) {
                const { error: profileError } = await supabase
                    .from('users')
                    .insert({
                        id: authData.user.id,
                        email: email,
                        password_hash: 'supabase_auth', // Managed by Supabase Auth
                        first_name: firstName,
                        last_name: lastName,
                        company: company,
                        email_verified: false
                    });

                if (profileError) console.error('Profile creation error:', profileError);
            }

            return { success: true, user: authData.user, message: 'Check your email to verify your account!' };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },

    // Login
    async login(email, password) {
        try {
            const { data, error } = await supabase.auth.signInWithPassword({
                email,
                password
            });

            if (error) throw error;

            // Update last login
            await supabase
                .from('users')
                .update({ last_login: new Date().toISOString() })
                .eq('id', data.user.id);

            // Log audit event
            await DalexorAudit.log('user_login', 'users', data.user.id);

            return { success: true, user: data.user };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },

    // Logout
    async logout() {
        try {
            await DalexorAudit.log('user_logout', 'users', this.currentUser?.id);
            const { error } = await supabase.auth.signOut();
            if (error) throw error;
            return { success: true };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },

    // Password reset request
    async requestPasswordReset(email) {
        try {
            const { error } = await supabase.auth.resetPasswordForEmail(email, {
                redirectTo: `${window.location.origin}/reset-password.html`
            });
            if (error) throw error;
            return { success: true, message: 'Check your email for reset instructions' };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },

    // Update password
    async updatePassword(newPassword) {
        try {
            const { error } = await supabase.auth.updateUser({
                password: newPassword
            });
            if (error) throw error;
            return { success: true, message: 'Password updated successfully' };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },

    // Get current user profile
    async getProfile() {
        if (!this.currentUser) return null;
        
        const { data, error } = await supabase
            .from('users')
            .select('*')
            .eq('id', this.currentUser.id)
            .single();

        return error ? null : data;
    },

    // Update UI based on auth state
    updateUI() {
        const loginBtn = document.querySelector('.nav-login-btn');
        const dashboardBtn = document.querySelector('.nav-dashboard-btn');
        const userMenu = document.querySelector('.user-menu');

        if (this.currentUser) {
            if (loginBtn) loginBtn.style.display = 'none';
            if (dashboardBtn) dashboardBtn.style.display = 'block';
            if (userMenu) userMenu.style.display = 'block';
        } else {
            if (loginBtn) loginBtn.style.display = 'block';
            if (dashboardBtn) dashboardBtn.style.display = 'none';
            if (userMenu) userMenu.style.display = 'none';
        }
    }
};

// ============================================
// LICENSE MANAGEMENT
// ============================================

const DalexorLicense = {
    // Generate a license key (format: DLX-XXXX-XXXX-XXXX-XXXX)
    generateKey() {
        const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        let key = 'DLX';
        
        for (let block = 0; block < 4; block++) {
            key += '-';
            for (let i = 0; i < 4; i++) {
                key += chars.charAt(Math.floor(Math.random() * chars.length));
            }
        }
        
        return key;
    },

    // Create a new license for user
    async createLicense(userId, subscriptionId, licenseType = 'standard') {
        try {
            const licenseKey = this.generateKey();
            
            // Calculate expiry based on subscription
            const { data: subscription } = await supabase
                .from('subscriptions')
                .select('end_date, plan')
                .eq('id', subscriptionId)
                .single();

            const { data, error } = await supabase
                .from('licenses')
                .insert({
                    user_id: userId,
                    subscription_id: subscriptionId,
                    license_key: licenseKey,
                    license_type: licenseType,
                    expires_at: subscription?.end_date,
                    max_activations: subscription?.plan === 'enterprise' ? 999 : (subscription?.plan === 'commercial' ? 5 : 1)
                })
                .select()
                .single();

            if (error) throw error;

            await DalexorAudit.log('license_created', 'licenses', data.id, { license_key: licenseKey });

            return { success: true, license: data };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },

    // Validate license key (called from desktop app)
    async validateLicense(licenseKey, hardwareId, machineInfo = {}) {
        try {
            // Find the license
            const { data: license, error } = await supabase
                .from('licenses')
                .select(`
                    *,
                    users (email, first_name, last_name),
                    subscriptions (plan, status, max_cameras, end_date)
                `)
                .eq('license_key', licenseKey)
                .single();

            if (error || !license) {
                return { valid: false, error: 'Invalid license key' };
            }

            // Check if license is active
            if (!license.is_active) {
                return { valid: false, error: 'License has been deactivated' };
            }

            // Check expiry
            if (license.expires_at && new Date(license.expires_at) < new Date()) {
                return { valid: false, error: 'License has expired' };
            }

            // Check subscription status
            if (license.subscriptions?.status !== 'active' && license.subscriptions?.status !== 'trial') {
                return { valid: false, error: 'Subscription is not active' };
            }

            // Check if already activated on different hardware
            if (license.hardware_id && license.hardware_id !== hardwareId) {
                // Check activation count
                if (license.current_activations >= license.max_activations) {
                    return { valid: false, error: 'Maximum activations reached. Deactivate another device first.' };
                }
            }

            // Activate/update the license
            const updateData = {
                hardware_id: hardwareId,
                hardware_info: machineInfo,
                machine_name: machineInfo.machine_name || null,
                os_info: machineInfo.os_info || null,
                app_version: machineInfo.app_version || null,
                activated: true,
                activated_at: license.activated_at || new Date().toISOString(),
                last_validated: new Date().toISOString(),
                last_heartbeat: new Date().toISOString(),
                validation_count: (license.validation_count || 0) + 1
            };

            // If new hardware, increment activation count
            if (!license.hardware_id || license.hardware_id !== hardwareId) {
                updateData.current_activations = (license.current_activations || 0) + 1;
                
                // Record activation
                await supabase
                    .from('license_activations')
                    .upsert({
                        license_id: license.id,
                        hardware_id: hardwareId,
                        machine_name: machineInfo.machine_name,
                        os_info: machineInfo.os_info,
                        app_version: machineInfo.app_version,
                        is_active: true
                    }, { onConflict: 'license_id,hardware_id' });
            }

            await supabase
                .from('licenses')
                .update(updateData)
                .eq('id', license.id);

            await DalexorAudit.log('license_validated', 'licenses', license.id, { hardware_id: hardwareId });

            return {
                valid: true,
                license: {
                    key: license.license_key,
                    type: license.license_type,
                    plan: license.subscriptions?.plan,
                    max_cameras: license.subscriptions?.max_cameras,
                    expires_at: license.expires_at,
                    user: {
                        email: license.users?.email,
                        name: `${license.users?.first_name} ${license.users?.last_name}`
                    }
                }
            };
        } catch (error) {
            return { valid: false, error: error.message };
        }
    },

    // Heartbeat - called periodically from desktop app
    async heartbeat(licenseKey, hardwareId) {
        try {
            const { error } = await supabase
                .from('licenses')
                .update({ last_heartbeat: new Date().toISOString() })
                .eq('license_key', licenseKey)
                .eq('hardware_id', hardwareId);

            return { success: !error };
        } catch (error) {
            return { success: false };
        }
    },

    // Deactivate license on a device
    async deactivate(licenseKey, hardwareId) {
        try {
            const { data: license } = await supabase
                .from('licenses')
                .select('id, current_activations')
                .eq('license_key', licenseKey)
                .single();

            if (!license) throw new Error('License not found');

            // Deactivate the specific activation
            await supabase
                .from('license_activations')
                .update({ is_active: false, deactivated_at: new Date().toISOString() })
                .eq('license_id', license.id)
                .eq('hardware_id', hardwareId);

            // Decrement activation count
            await supabase
                .from('licenses')
                .update({ 
                    current_activations: Math.max(0, (license.current_activations || 1) - 1),
                    hardware_id: null // Clear primary hardware
                })
                .eq('id', license.id);

            await DalexorAudit.log('license_deactivated', 'licenses', license.id, { hardware_id: hardwareId });

            return { success: true };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },

    // Get user's licenses
    async getUserLicenses(userId) {
        const { data, error } = await supabase
            .from('licenses')
            .select(`
                *,
                subscriptions (plan, status, max_cameras),
                license_activations (hardware_id, machine_name, is_active, activated_at)
            `)
            .eq('user_id', userId)
            .order('created_at', { ascending: false });

        return error ? [] : data;
    }
};

// ============================================
// CONTACT & DEMO FORMS
// ============================================

const DalexorForms = {
    // Submit contact form
    async submitContact(formData) {
        try {
            const { data, error } = await supabase
                .from('contact_submissions')
                .insert({
                    name: formData.name,
                    email: formData.email,
                    company: formData.company || null,
                    phone: formData.phone || null,
                    subject: formData.subject || null,
                    message: formData.message,
                    source: 'website'
                })
                .select()
                .single();

            if (error) throw error;

            return { success: true, message: 'Thank you! We\'ll get back to you soon.' };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },

    // Submit demo request
    async submitDemoRequest(formData) {
        try {
            const { data, error } = await supabase
                .from('demo_requests')
                .insert({
                    name: formData.name,
                    email: formData.email,
                    company: formData.company,
                    phone: formData.phone || null,
                    job_title: formData.jobTitle || null,
                    company_size: formData.companySize || null,
                    use_case: formData.useCase || null,
                    message: formData.message || null
                })
                .select()
                .single();

            if (error) throw error;

            return { success: true, message: 'Demo request received! We\'ll contact you within 24 hours.' };
        } catch (error) {
            return { success: false, error: error.message };
        }
    },

    // Subscribe to newsletter
    async subscribeNewsletter(email, name = null) {
        try {
            const { error } = await supabase
                .from('newsletter_subscribers')
                .upsert({
                    email: email,
                    name: name,
                    status: 'active',
                    subscribed_at: new Date().toISOString()
                }, { onConflict: 'email' });

            if (error) throw error;

            return { success: true, message: 'Successfully subscribed!' };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }
};

// ============================================
// PRICING & SUBSCRIPTIONS
// ============================================

const DalexorPricing = {
    // Get all pricing plans
    async getPlans() {
        const { data, error } = await supabase
            .from('pricing_plans')
            .select('*')
            .eq('is_active', true)
            .order('sort_order');

        return error ? [] : data;
    },

    // Get user's subscription
    async getUserSubscription(userId) {
        const { data, error } = await supabase
            .from('subscriptions')
            .select('*')
            .eq('user_id', userId)
            .eq('status', 'active')
            .single();

        return error ? null : data;
    },

    // Create trial subscription
    async createTrialSubscription(userId, plan = 'home') {
        try {
            const trialDays = 14;
            const trialEnd = new Date();
            trialEnd.setDate(trialEnd.getDate() + trialDays);

            const { data: subscription, error } = await supabase
                .from('subscriptions')
                .insert({
                    user_id: userId,
                    plan: plan,
                    status: 'trial',
                    max_cameras: plan === 'home' ? 8 : (plan === 'commercial' ? 32 : 9999),
                    trial_end_date: trialEnd.toISOString(),
                    end_date: trialEnd.toISOString(),
                    price_cents: 0
                })
                .select()
                .single();

            if (error) throw error;

            // Auto-generate license
            const licenseResult = await DalexorLicense.createLicense(userId, subscription.id, 'trial');

            return { 
                success: true, 
                subscription, 
                license: licenseResult.license 
            };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }
};

// ============================================
// AUDIT LOGGING
// ============================================

const DalexorAudit = {
    async log(action, resourceType = null, resourceId = null, details = null) {
        try {
            await supabase
                .from('audit_log')
                .insert({
                    user_id: DalexorAuth.currentUser?.id || null,
                    action: action,
                    resource_type: resourceType,
                    resource_id: resourceId,
                    details: details ? JSON.stringify(details) : null
                });
        } catch (error) {
            console.error('Audit log error:', error);
        }
    }
};

// ============================================
// FORM HANDLERS - Auto-attach to forms
// ============================================

document.addEventListener('DOMContentLoaded', () => {
    // Initialize auth
    DalexorAuth.init();

    // Contact form
    const contactForm = document.getElementById('contact-form');
    if (contactForm) {
        contactForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const btn = contactForm.querySelector('button[type="submit"]');
            const originalText = btn.textContent;
            btn.disabled = true;
            btn.innerHTML = '<span class="spinner"></span> Sending...';

            const result = await DalexorForms.submitContact({
                name: contactForm.querySelector('[name="name"]')?.value,
                email: contactForm.querySelector('[name="email"]')?.value,
                company: contactForm.querySelector('[name="company"]')?.value,
                phone: contactForm.querySelector('[name="phone"]')?.value,
                subject: contactForm.querySelector('[name="subject"]')?.value,
                message: contactForm.querySelector('[name="message"]')?.value
            });

            btn.innerHTML = result.success ? '✓ Sent!' : '✗ Error';
            btn.classList.add(result.success ? 'success' : 'error');
            
            if (result.success) {
                contactForm.reset();
                showNotification(result.message, 'success');
            } else {
                showNotification(result.error, 'error');
            }

            setTimeout(() => {
                btn.disabled = false;
                btn.textContent = originalText;
                btn.classList.remove('success', 'error');
            }, 3000);
        });
    }

    // Demo request form
    const demoForm = document.getElementById('demo-form');
    if (demoForm) {
        demoForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const btn = demoForm.querySelector('button[type="submit"]');
            const originalText = btn.textContent;
            btn.disabled = true;
            btn.innerHTML = '<span class="spinner"></span> Submitting...';

            const result = await DalexorForms.submitDemoRequest({
                name: demoForm.querySelector('[name="name"]')?.value,
                email: demoForm.querySelector('[name="email"]')?.value,
                company: demoForm.querySelector('[name="company"]')?.value,
                phone: demoForm.querySelector('[name="phone"]')?.value,
                jobTitle: demoForm.querySelector('[name="job_title"]')?.value,
                companySize: demoForm.querySelector('[name="company_size"]')?.value,
                useCase: demoForm.querySelector('[name="use_case"]')?.value,
                message: demoForm.querySelector('[name="message"]')?.value
            });

            btn.innerHTML = result.success ? '✓ Submitted!' : '✗ Error';
            btn.classList.add(result.success ? 'success' : 'error');
            
            if (result.success) {
                demoForm.reset();
                showNotification(result.message, 'success');
            } else {
                showNotification(result.error, 'error');
            }

            setTimeout(() => {
                btn.disabled = false;
                btn.textContent = originalText;
                btn.classList.remove('success', 'error');
            }, 3000);
        });
    }

    // Newsletter form
    const newsletterForm = document.getElementById('newsletter-form');
    if (newsletterForm) {
        newsletterForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const email = newsletterForm.querySelector('[name="email"]')?.value;
            const result = await DalexorForms.subscribeNewsletter(email);
            
            if (result.success) {
                newsletterForm.reset();
                showNotification(result.message, 'success');
            } else {
                showNotification(result.error, 'error');
            }
        });
    }

    // Login form
    const loginForm = document.getElementById('login-form');
    if (loginForm) {
        loginForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const btn = loginForm.querySelector('button[type="submit"]');
            btn.disabled = true;
            btn.innerHTML = '<span class="spinner"></span> Logging in...';

            const result = await DalexorAuth.login(
                loginForm.querySelector('[name="email"]')?.value,
                loginForm.querySelector('[name="password"]')?.value
            );

            if (result.success) {
                window.location.href = '/dashboard.html';
            } else {
                showNotification(result.error, 'error');
                btn.disabled = false;
                btn.textContent = 'Login';
            }
        });
    }

    // Register form
    const registerForm = document.getElementById('register-form');
    if (registerForm) {
        registerForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const btn = registerForm.querySelector('button[type="submit"]');
            btn.disabled = true;
            btn.innerHTML = '<span class="spinner"></span> Creating account...';

            const result = await DalexorAuth.register(
                registerForm.querySelector('[name="email"]')?.value,
                registerForm.querySelector('[name="password"]')?.value,
                registerForm.querySelector('[name="first_name"]')?.value,
                registerForm.querySelector('[name="last_name"]')?.value,
                registerForm.querySelector('[name="company"]')?.value
            );

            if (result.success) {
                showNotification(result.message, 'success');
                setTimeout(() => {
                    window.location.href = '/login.html';
                }, 2000);
            } else {
                showNotification(result.error, 'error');
                btn.disabled = false;
                btn.textContent = 'Create Account';
            }
        });
    }
});

// ============================================
// UTILITY FUNCTIONS
// ============================================

function showNotification(message, type = 'info') {
    // Remove existing notifications
    document.querySelectorAll('.notification').forEach(n => n.remove());

    const notification = document.createElement('div');
    notification.className = `notification notification-${type}`;
    notification.innerHTML = `
        <span>${message}</span>
        <button onclick="this.parentElement.remove()">&times;</button>
    `;
    
    document.body.appendChild(notification);

    // Auto-remove after 5 seconds
    setTimeout(() => notification.remove(), 5000);
}

// Add notification styles dynamically
const notificationStyles = document.createElement('style');
notificationStyles.textContent = `
    .notification {
        position: fixed;
        top: 20px;
        right: 20px;
        padding: 1rem 1.5rem;
        border-radius: 8px;
        background: #1a1a2e;
        border: 1px solid rgba(139, 92, 246, 0.3);
        color: white;
        display: flex;
        align-items: center;
        gap: 1rem;
        z-index: 10000;
        animation: slideIn 0.3s ease;
        max-width: 400px;
    }
    .notification-success { border-color: #10b981; background: rgba(16, 185, 129, 0.1); }
    .notification-error { border-color: #ef4444; background: rgba(239, 68, 68, 0.1); }
    .notification button {
        background: none;
        border: none;
        color: white;
        font-size: 1.2rem;
        cursor: pointer;
        opacity: 0.7;
    }
    .notification button:hover { opacity: 1; }
    @keyframes slideIn {
        from { transform: translateX(100%); opacity: 0; }
        to { transform: translateX(0); opacity: 1; }
    }
    .spinner {
        display: inline-block;
        width: 16px;
        height: 16px;
        border: 2px solid rgba(255,255,255,0.3);
        border-top-color: white;
        border-radius: 50%;
        animation: spin 0.8s linear infinite;
    }
    @keyframes spin {
        to { transform: rotate(360deg); }
    }
`;
document.head.appendChild(notificationStyles);

// Export for use in other scripts
window.DalexorAuth = DalexorAuth;
window.DalexorLicense = DalexorLicense;
window.DalexorForms = DalexorForms;
window.DalexorPricing = DalexorPricing;
