#!/usr/bin/env node
/**
 * DALEXOR - Build Script
 * Injects Vercel environment variables into env-config.js
 * Run this during Vercel build: node build.js
 */

const fs = require('fs');
const path = require('path');

// Get environment variables from Vercel
const SUPABASE_URL = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

// Validate required env vars
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('❌ ERROR: Missing required environment variables!');
    console.error('   Set SUPABASE_URL and SUPABASE_ANON_KEY in Vercel Dashboard');
    console.error('   Project Settings > Environment Variables');
    process.exit(1);
}

// Generate env-config.js content
const envConfigContent = `/* ============================================
   DALEXOR - Environment Configuration
   AUTO-GENERATED BY build.js - DO NOT EDIT
   ============================================ */

window.__ENV__ = {
    SUPABASE_URL: '${SUPABASE_URL}',
    SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}'
};
`;

// Ensure js/ directory exists
const jsDir = path.join(__dirname, 'js');
if (!fs.existsSync(jsDir)) {
    fs.mkdirSync(jsDir, { recursive: true });
    console.log('📁 Created js/ directory');
}

// Write to js/env-config.js
const outputPath = path.join(jsDir, 'env-config.js');
fs.writeFileSync(outputPath, envConfigContent);

console.log('✅ Environment config generated successfully!');
console.log(`   SUPABASE_URL: ${SUPABASE_URL}`);
console.log(`   SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY.substring(0, 20)}...`);
